- job-template:
    name: 'ops-config-yaml-check-{platform}'
    node: openswitch
    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor
    builders:
        - revoke-sudo
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: '{platform}'

- job:
    name: 'ops-config-yaml-gate-as5712'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: 'as5712'

- job:
    name: 'ops-config-yaml-gate-genericx86-64'
    node: vsi

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: 'genericx86-64'
        - module-cttest:
            module: 'ops-config-yaml'
            platform: 'genericx86-64'

    publishers:
        - junit:
            results: 'build/*test*.xml'

- job-group:
    name: 'ops-config-yaml-jobs'
    jobs:
      - 'ops-config-yaml-check-{platform}'
